# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ''

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  displayName: 'Prepare SonarCloud Code Analysis'
  enabled: false
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'mattsharpe-github'
    scannerMode: 'MSBuild'
    projectKey: 'mattsharpe_AdventOfCode'
    projectName: 'Advent Of Code'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'AdventOfCode.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\Advent*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  enabled: false
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    testRunTitle: 'Unit Tests'

- task: SonarCloudAnalyze@1
  enabled: false
  displayName: 'Run SonarCloud Code Analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'
  enabled: false
  inputs:
    pollingTimeoutSec: '300'